import { escapeHtml, type EnquiryEmailBrand } from '../contact/enquiry.ts';
import { pickupAddress, pickupWindow, type CustomerOrder } from '../account/orders.ts';
import { money } from '../bag.ts';

export function orderConfirmationEmail(order: CustomerOrder, brand: EnquiryEmailBrand) {
  const reference = `Order #${order.order_number}`;
  const orderUrl = new URL('/account', brand.siteUrl);
  orderUrl.search = new URLSearchParams({ view: 'orders', order: order.id }).toString();
  const address = pickupAddress(order.pickup_location);
  const window = pickupWindow(order);
  const totals = [['Items and extras', order.subtotal_pence], ['Service fee', order.service_fee_pence], ['Packaging', order.packaging_fee_pence], ['Total paid', order.total_pence]] as const;
  const itemsText = order.order_items.map((item) => `${item.quantity} x ${item.item_name} - ${money(item.line_total_pence)}${item.order_item_modifiers.map((choice) => `\n  ${choice.group_name}: ${choice.option_name}`).join('')}`).join('\n');
  const itemsHtml = order.order_items.map((item) => `<tr><td style="padding:16px 0;border-bottom:1px solid #dedfd9;overflow-wrap:anywhere;"><strong>${item.quantity} x ${escapeHtml(item.item_name)}</strong>${item.order_item_modifiers.map((choice) => `<div style="margin-top:5px;font-size:13px;line-height:1.5;color:#5e615b;">${escapeHtml(choice.group_name)}: ${escapeHtml(choice.option_name)}</div>`).join('')}</td><td align="right" valign="top" style="padding:16px 0 16px 12px;border-bottom:1px solid #dedfd9;white-space:nowrap;">${money(item.line_total_pence)}</td></tr>`).join('');
  const socialLinks = [[brand.instagramUrl, 'Instagram'], [brand.facebookUrl, 'Facebook']].filter((entry): entry is [string, string] => Boolean(entry[0]));
  return {
    subject: `${reference} confirmed for pickup | Papa's Tacos`,
    text: `PAPA'S TACOS\nPAYMENT RECEIVED - ORDER CONFIRMED\n\n${reference.toUpperCase()}\nShow this order number to our staff when collecting.\n\nThanks, ${order.customer_name}. Your payment has been received.\n\nPICKUP\n${window}\n${address}\n\nYOUR ORDER\n${itemsText}\n\n${totals.map(([label, value]) => `${label}: ${money(value)}`).join('\n')}${order.customer_note ? `\n\nYOUR NOTE\n${order.customer_note}` : ''}\n\nView your order and download your receipt (sign in required):\n${orderUrl.href}\n\nThis confirms your order, not that it is ready. Please collect at your selected pickup time.\n\nPapa's Tacos\n${brand.siteUrl}${socialLinks.map(([url, label]) => `\n${label}: ${url}`).join('')}`,
    html: `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${reference} confirmed | Papa's Tacos</title><style>@media(max-width:600px){.email-shell{padding:0!important}.email-main{padding:28px 20px!important}.email-header{padding:24px 20px!important}.email-footer{padding:26px 20px!important}}</style></head>
<body style="margin:0;background:#eeefeb;color:#181918;font-family:Arial,Helvetica,sans-serif;"><div style="display:none;max-height:0;overflow:hidden;opacity:0;">${reference} confirmed. Pickup ${escapeHtml(window)}.</div>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#eeefeb;"><tr><td class="email-shell" align="center" style="padding:32px 12px;"><table role="presentation" width="640" cellspacing="0" cellpadding="0" style="width:100%;max-width:640px;background:#ffffff;border-collapse:collapse;">
<tr><td class="email-header" align="center" style="padding:28px 40px;background:#181918;border-bottom:4px solid #f0bb7d;"><a href="${escapeHtml(brand.siteUrl)}"><img src="${escapeHtml(brand.logoUrl)}" width="340" alt="Papa's Tacos" style="display:block;width:340px;max-width:100%;height:auto;border:0;"></a></td></tr>
<tr><td class="email-main" style="padding:40px 48px;"><p style="margin:0 0 12px;color:#087b55;font-size:12px;font-weight:bold;text-transform:uppercase;">Payment received</p><h1 style="margin:0;font-size:28px;line-height:1.25;">Your pickup order is confirmed.</h1><p style="font-size:15px;line-height:1.65;">Thanks, ${escapeHtml(order.customer_name)}. We have received your order and payment.</p>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:24px 0;background:#181918;"><tr><td align="center" style="padding:28px 16px;"><p style="margin:0;color:#f0bb7d;font-size:32px;font-weight:bold;line-height:1.3;overflow-wrap:anywhere;">${reference}</p><p style="margin:10px 0 0;color:#ffffff;font-size:14px;line-height:1.6;">Show this order number to our staff when collecting.</p></td></tr></table>
<h2 style="font-size:17px;margin:28px 0 12px;">Pickup details</h2><p style="margin:0 0 8px;font-size:16px;line-height:1.6;font-weight:bold;">${escapeHtml(window)}</p><p style="margin:0;font-size:15px;line-height:1.65;overflow-wrap:anywhere;">${escapeHtml(address)}</p><p style="font-size:13px;line-height:1.65;color:#5e615b;">This confirms your order, not that it is ready. Please collect at your selected pickup time.</p>
<h2 style="font-size:17px;margin:28px 0 8px;">Your order</h2><table width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;font-size:15px;line-height:1.5;">${itemsHtml}</table>
<table width="100%" cellspacing="0" cellpadding="0" style="margin-top:16px;font-size:14px;line-height:1.6;">${totals.map(([label, value]) => `<tr><td style="padding:6px 0;${label === 'Total paid' ? 'font-weight:bold;font-size:18px;' : ''}">${label}</td><td align="right" style="padding:6px 0;white-space:nowrap;${label === 'Total paid' ? 'font-weight:bold;font-size:18px;' : ''}">${money(value)}</td></tr>`).join('')}</table>
${order.customer_note ? `<h2 style="font-size:17px;margin:28px 0 10px;">Your note</h2><p style="font-size:14px;line-height:1.65;white-space:pre-wrap;overflow-wrap:anywhere;">${escapeHtml(order.customer_note)}</p>` : ''}
<p style="margin:30px 0 12px;"><a href="${escapeHtml(orderUrl.href)}" style="display:inline-block;padding:15px 22px;background:#087b55;color:#ffffff;text-decoration:none;font-size:15px;font-weight:bold;border-radius:4px;">View order and receipt</a></p><p style="font-size:12px;line-height:1.6;color:#5e615b;">Sign in to view your order updates and download your receipt.</p></td></tr>
<tr><td class="email-footer" align="center" style="padding:28px 40px;background:#181918;"><p style="margin:0;font-size:16px;color:#f0bb7d;font-weight:bold;">Papa's Tacos</p><p style="margin:10px 0;color:#ffffff;font-size:13px;">Mexican soul. Street food spirit. Made fresh.</p>${socialLinks.map(([url, label]) => `<a href="${escapeHtml(url)}" style="display:inline-block;padding:8px;color:#f0bb7d;font-size:13px;">${label}</a>`).join('')}<p style="margin:14px 0 0;color:#bfc2b9;font-size:11px;">&copy; ${new Date(order.created_at).getUTCFullYear()} Papa's Tacos. All rights reserved.</p></td></tr></table></td></tr></table></body></html>`,
  };
}